version: '2.1'
services:
  app:
    build: .
    links:
      - db
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./:/app
    ports:
      - '8000:80'
  db:
    image: postgres:10
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
