version: '3.7'
services:
  app:
    build: .
    links:
      - db
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - '8000:80'
  db:
    image: postgres:10
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
