version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    links:
      - db
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    image: postgres:10
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example